language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:0.* --dev
  - composer update $DEPENDENCIES

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v -c .coveralls.yml
